// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

/**
 * Protobuf type {@code HelloWorld}
 */
public  final class HelloWorld extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HelloWorld)
    HelloWorldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HelloWorld.newBuilder() to construct.
  private HelloWorld(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HelloWorld() {
    strHello_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new HelloWorld();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HelloWorld(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            strHello_ = s;
            break;
          }
          case 16: {

            age_ = input.readInt32();
            break;
          }
          case 29: {

            weight_ = input.readFloat();
            break;
          }
          case 37: {

            size_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Test.internal_static_HelloWorld_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Test.internal_static_HelloWorld_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            HelloWorld.class, Builder.class);
  }

  public static final int STRHELLO_FIELD_NUMBER = 1;
  private volatile Object strHello_;
  /**
   * <code>string strHello = 1;</code>
   * @return The strHello.
   */
  public String getStrHello() {
    Object ref = strHello_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      strHello_ = s;
      return s;
    }
  }
  /**
   * <code>string strHello = 1;</code>
   * @return The bytes for strHello.
   */
  public com.google.protobuf.ByteString
      getStrHelloBytes() {
    Object ref = strHello_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      strHello_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  public int getAge() {
    return age_;
  }

  public static final int WEIGHT_FIELD_NUMBER = 3;
  private float weight_;
  /**
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  public float getWeight() {
    return weight_;
  }

  public static final int SIZE_FIELD_NUMBER = 4;
  private float size_;
  /**
   * <code>float size = 4;</code>
   * @return The size.
   */
  public float getSize() {
    return size_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStrHelloBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, strHello_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (weight_ != 0F) {
      output.writeFloat(3, weight_);
    }
    if (size_ != 0F) {
      output.writeFloat(4, size_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStrHelloBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, strHello_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (weight_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, weight_);
    }
    if (size_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, size_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof HelloWorld)) {
      return super.equals(obj);
    }
    HelloWorld other = (HelloWorld) obj;

    if (!getStrHello()
        .equals(other.getStrHello())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (Float.floatToIntBits(getWeight())
        != Float.floatToIntBits(
            other.getWeight())) return false;
    if (Float.floatToIntBits(getSize())
        != Float.floatToIntBits(
            other.getSize())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STRHELLO_FIELD_NUMBER;
    hash = (53 * hash) + getStrHello().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getWeight());
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static HelloWorld parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HelloWorld parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HelloWorld parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HelloWorld parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HelloWorld parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HelloWorld parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HelloWorld parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HelloWorld parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static HelloWorld parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static HelloWorld parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static HelloWorld parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HelloWorld parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(HelloWorld prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HelloWorld}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HelloWorld)
      HelloWorldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test.internal_static_HelloWorld_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test.internal_static_HelloWorld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HelloWorld.class, Builder.class);
    }

    // Construct using HelloWorld.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      strHello_ = "";

      age_ = 0;

      weight_ = 0F;

      size_ = 0F;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Test.internal_static_HelloWorld_descriptor;
    }

    @Override
    public HelloWorld getDefaultInstanceForType() {
      return HelloWorld.getDefaultInstance();
    }

    @Override
    public HelloWorld build() {
      HelloWorld result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public HelloWorld buildPartial() {
      HelloWorld result = new HelloWorld(this);
      result.strHello_ = strHello_;
      result.age_ = age_;
      result.weight_ = weight_;
      result.size_ = size_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof HelloWorld) {
        return mergeFrom((HelloWorld)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(HelloWorld other) {
      if (other == HelloWorld.getDefaultInstance()) return this;
      if (!other.getStrHello().isEmpty()) {
        strHello_ = other.strHello_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.getWeight() != 0F) {
        setWeight(other.getWeight());
      }
      if (other.getSize() != 0F) {
        setSize(other.getSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      HelloWorld parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (HelloWorld) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object strHello_ = "";
    /**
     * <code>string strHello = 1;</code>
     * @return The strHello.
     */
    public String getStrHello() {
      Object ref = strHello_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        strHello_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string strHello = 1;</code>
     * @return The bytes for strHello.
     */
    public com.google.protobuf.ByteString
        getStrHelloBytes() {
      Object ref = strHello_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        strHello_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string strHello = 1;</code>
     * @param value The strHello to set.
     * @return This builder for chaining.
     */
    public Builder setStrHello(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      strHello_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string strHello = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStrHello() {
      
      strHello_ = getDefaultInstance().getStrHello();
      onChanged();
      return this;
    }
    /**
     * <code>string strHello = 1;</code>
     * @param value The bytes for strHello to set.
     * @return This builder for chaining.
     */
    public Builder setStrHelloBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      strHello_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private float weight_ ;
    /**
     * <code>float weight = 3;</code>
     * @return The weight.
     */
    public float getWeight() {
      return weight_;
    }
    /**
     * <code>float weight = 3;</code>
     * @param value The weight to set.
     * @return This builder for chaining.
     */
    public Builder setWeight(float value) {
      
      weight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float weight = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeight() {
      
      weight_ = 0F;
      onChanged();
      return this;
    }

    private float size_ ;
    /**
     * <code>float size = 4;</code>
     * @return The size.
     */
    public float getSize() {
      return size_;
    }
    /**
     * <code>float size = 4;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(float value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float size = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = 0F;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HelloWorld)
  }

  // @@protoc_insertion_point(class_scope:HelloWorld)
  private static final HelloWorld DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HelloWorld();
  }

  public static HelloWorld getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HelloWorld>
      PARSER = new com.google.protobuf.AbstractParser<HelloWorld>() {
    @Override
    public HelloWorld parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HelloWorld(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HelloWorld> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<HelloWorld> getParserForType() {
    return PARSER;
  }

  @Override
  public HelloWorld getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

