// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

public interface TestHelloWorldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestHelloWorld)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string strHello = 1;</code>
   * @return The strHello.
   */
  java.lang.String getStrHello();
  /**
   * <code>string strHello = 1;</code>
   * @return The bytes for strHello.
   */
  com.google.protobuf.ByteString
      getStrHelloBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>float weight = 3;</code>
   * @return The weight.
   */
  float getWeight();

  /**
   * <code>float size = 4;</code>
   * @return The size.
   */
  float getSize();
}
