// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IMC.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IMC_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IMC_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IMC_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IMC_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
namespace imcPersonne {
class imcPersonneRequest;
class imcPersonneRequestDefaultTypeInternal;
extern imcPersonneRequestDefaultTypeInternal _imcPersonneRequest_default_instance_;
class imcResponse;
class imcResponseDefaultTypeInternal;
extern imcResponseDefaultTypeInternal _imcResponse_default_instance_;
}  // namespace imcPersonne
PROTOBUF_NAMESPACE_OPEN
template<> ::imcPersonne::imcPersonneRequest* Arena::CreateMaybeMessage<::imcPersonne::imcPersonneRequest>(Arena*);
template<> ::imcPersonne::imcResponse* Arena::CreateMaybeMessage<::imcPersonne::imcResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace imcPersonne {

// ===================================================================

class imcPersonneRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:imcPersonne.imcPersonneRequest) */ {
 public:
  inline imcPersonneRequest() : imcPersonneRequest(nullptr) {};
  virtual ~imcPersonneRequest();

  imcPersonneRequest(const imcPersonneRequest& from);
  imcPersonneRequest(imcPersonneRequest&& from) noexcept
    : imcPersonneRequest() {
    *this = ::std::move(from);
  }

  inline imcPersonneRequest& operator=(const imcPersonneRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline imcPersonneRequest& operator=(imcPersonneRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const imcPersonneRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const imcPersonneRequest* internal_default_instance() {
    return reinterpret_cast<const imcPersonneRequest*>(
               &_imcPersonneRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(imcPersonneRequest& a, imcPersonneRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(imcPersonneRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(imcPersonneRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline imcPersonneRequest* New() const final {
    return CreateMaybeMessage<imcPersonneRequest>(nullptr);
  }

  imcPersonneRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<imcPersonneRequest>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const imcPersonneRequest& from);
  void MergeFrom(const imcPersonneRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(imcPersonneRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "imcPersonne.imcPersonneRequest";
  }
  protected:
  explicit imcPersonneRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStrNameFieldNumber = 1,
    kAgeFieldNumber = 2,
    kWeightFieldNumber = 3,
    kSizeFieldNumber = 4,
  };
  // string strName = 1;
  void clear_strname();
  const std::string& strname() const;
  void set_strname(const std::string& value);
  void set_strname(std::string&& value);
  void set_strname(const char* value);
  void set_strname(const char* value, size_t size);
  std::string* mutable_strname();
  std::string* release_strname();
  void set_allocated_strname(std::string* strname);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_strname();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_strname(
      std::string* strname);
  private:
  const std::string& _internal_strname() const;
  void _internal_set_strname(const std::string& value);
  std::string* _internal_mutable_strname();
  public:

  // int32 age = 2;
  void clear_age();
  ::PROTOBUF_NAMESPACE_ID::int32 age() const;
  void set_age(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_age() const;
  void _internal_set_age(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // float weight = 3;
  void clear_weight();
  float weight() const;
  void set_weight(float value);
  private:
  float _internal_weight() const;
  void _internal_set_weight(float value);
  public:

  // float size = 4;
  void clear_size();
  float size() const;
  void set_size(float value);
  private:
  float _internal_size() const;
  void _internal_set_size(float value);
  public:

  // @@protoc_insertion_point(class_scope:imcPersonne.imcPersonneRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr strname_;
  ::PROTOBUF_NAMESPACE_ID::int32 age_;
  float weight_;
  float size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMC_2eproto;
};
// -------------------------------------------------------------------

class imcResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:imcPersonne.imcResponse) */ {
 public:
  inline imcResponse() : imcResponse(nullptr) {};
  virtual ~imcResponse();

  imcResponse(const imcResponse& from);
  imcResponse(imcResponse&& from) noexcept
    : imcResponse() {
    *this = ::std::move(from);
  }

  inline imcResponse& operator=(const imcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline imcResponse& operator=(imcResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const imcResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const imcResponse* internal_default_instance() {
    return reinterpret_cast<const imcResponse*>(
               &_imcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(imcResponse& a, imcResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(imcResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(imcResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline imcResponse* New() const final {
    return CreateMaybeMessage<imcResponse>(nullptr);
  }

  imcResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<imcResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const imcResponse& from);
  void MergeFrom(const imcResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(imcResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "imcPersonne.imcResponse";
  }
  protected:
  explicit imcResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResponseFieldNumber = 1,
  };
  // string response = 1;
  void clear_response();
  const std::string& response() const;
  void set_response(const std::string& value);
  void set_response(std::string&& value);
  void set_response(const char* value);
  void set_response(const char* value, size_t size);
  std::string* mutable_response();
  std::string* release_response();
  void set_allocated_response(std::string* response);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_response();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_response(
      std::string* response);
  private:
  const std::string& _internal_response() const;
  void _internal_set_response(const std::string& value);
  std::string* _internal_mutable_response();
  public:

  // @@protoc_insertion_point(class_scope:imcPersonne.imcResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_IMC_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// imcPersonneRequest

// string strName = 1;
inline void imcPersonneRequest::clear_strname() {
  strname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& imcPersonneRequest::strname() const {
  // @@protoc_insertion_point(field_get:imcPersonne.imcPersonneRequest.strName)
  return _internal_strname();
}
inline void imcPersonneRequest::set_strname(const std::string& value) {
  _internal_set_strname(value);
  // @@protoc_insertion_point(field_set:imcPersonne.imcPersonneRequest.strName)
}
inline std::string* imcPersonneRequest::mutable_strname() {
  // @@protoc_insertion_point(field_mutable:imcPersonne.imcPersonneRequest.strName)
  return _internal_mutable_strname();
}
inline const std::string& imcPersonneRequest::_internal_strname() const {
  return strname_.Get();
}
inline void imcPersonneRequest::_internal_set_strname(const std::string& value) {
  
  strname_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void imcPersonneRequest::set_strname(std::string&& value) {
  
  strname_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:imcPersonne.imcPersonneRequest.strName)
}
inline void imcPersonneRequest::set_strname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  strname_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:imcPersonne.imcPersonneRequest.strName)
}
inline void imcPersonneRequest::set_strname(const char* value,
    size_t size) {
  
  strname_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:imcPersonne.imcPersonneRequest.strName)
}
inline std::string* imcPersonneRequest::_internal_mutable_strname() {
  
  return strname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* imcPersonneRequest::release_strname() {
  // @@protoc_insertion_point(field_release:imcPersonne.imcPersonneRequest.strName)
  return strname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void imcPersonneRequest::set_allocated_strname(std::string* strname) {
  if (strname != nullptr) {
    
  } else {
    
  }
  strname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), strname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:imcPersonne.imcPersonneRequest.strName)
}
inline std::string* imcPersonneRequest::unsafe_arena_release_strname() {
  // @@protoc_insertion_point(field_unsafe_arena_release:imcPersonne.imcPersonneRequest.strName)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return strname_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void imcPersonneRequest::unsafe_arena_set_allocated_strname(
    std::string* strname) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (strname != nullptr) {
    
  } else {
    
  }
  strname_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      strname, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:imcPersonne.imcPersonneRequest.strName)
}

// int32 age = 2;
inline void imcPersonneRequest::clear_age() {
  age_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 imcPersonneRequest::_internal_age() const {
  return age_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 imcPersonneRequest::age() const {
  // @@protoc_insertion_point(field_get:imcPersonne.imcPersonneRequest.age)
  return _internal_age();
}
inline void imcPersonneRequest::_internal_set_age(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  age_ = value;
}
inline void imcPersonneRequest::set_age(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:imcPersonne.imcPersonneRequest.age)
}

// float weight = 3;
inline void imcPersonneRequest::clear_weight() {
  weight_ = 0;
}
inline float imcPersonneRequest::_internal_weight() const {
  return weight_;
}
inline float imcPersonneRequest::weight() const {
  // @@protoc_insertion_point(field_get:imcPersonne.imcPersonneRequest.weight)
  return _internal_weight();
}
inline void imcPersonneRequest::_internal_set_weight(float value) {
  
  weight_ = value;
}
inline void imcPersonneRequest::set_weight(float value) {
  _internal_set_weight(value);
  // @@protoc_insertion_point(field_set:imcPersonne.imcPersonneRequest.weight)
}

// float size = 4;
inline void imcPersonneRequest::clear_size() {
  size_ = 0;
}
inline float imcPersonneRequest::_internal_size() const {
  return size_;
}
inline float imcPersonneRequest::size() const {
  // @@protoc_insertion_point(field_get:imcPersonne.imcPersonneRequest.size)
  return _internal_size();
}
inline void imcPersonneRequest::_internal_set_size(float value) {
  
  size_ = value;
}
inline void imcPersonneRequest::set_size(float value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:imcPersonne.imcPersonneRequest.size)
}

// -------------------------------------------------------------------

// imcResponse

// string response = 1;
inline void imcResponse::clear_response() {
  response_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& imcResponse::response() const {
  // @@protoc_insertion_point(field_get:imcPersonne.imcResponse.response)
  return _internal_response();
}
inline void imcResponse::set_response(const std::string& value) {
  _internal_set_response(value);
  // @@protoc_insertion_point(field_set:imcPersonne.imcResponse.response)
}
inline std::string* imcResponse::mutable_response() {
  // @@protoc_insertion_point(field_mutable:imcPersonne.imcResponse.response)
  return _internal_mutable_response();
}
inline const std::string& imcResponse::_internal_response() const {
  return response_.Get();
}
inline void imcResponse::_internal_set_response(const std::string& value) {
  
  response_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void imcResponse::set_response(std::string&& value) {
  
  response_.SetLite(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:imcPersonne.imcResponse.response)
}
inline void imcResponse::set_response(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  response_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:imcPersonne.imcResponse.response)
}
inline void imcResponse::set_response(const char* value,
    size_t size) {
  
  response_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:imcPersonne.imcResponse.response)
}
inline std::string* imcResponse::_internal_mutable_response() {
  
  return response_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* imcResponse::release_response() {
  // @@protoc_insertion_point(field_release:imcPersonne.imcResponse.response)
  return response_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void imcResponse::set_allocated_response(std::string* response) {
  if (response != nullptr) {
    
  } else {
    
  }
  response_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), response,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:imcPersonne.imcResponse.response)
}
inline std::string* imcResponse::unsafe_arena_release_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:imcPersonne.imcResponse.response)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return response_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void imcResponse::unsafe_arena_set_allocated_response(
    std::string* response) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (response != nullptr) {
    
  } else {
    
  }
  response_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      response, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:imcPersonne.imcResponse.response)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace imcPersonne

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IMC_2eproto
