// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: IMC.proto

#include "IMC.pb.h"
#include "IMC.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace imcPersonne {

static const char* imcService_method_names[] = {
  "/imcPersonne.imcService/IMCRequest",
};

std::unique_ptr< imcService::Stub> imcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< imcService::Stub> stub(new imcService::Stub(channel));
  return stub;
}

imcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_IMCRequest_(imcService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status imcService::Stub::IMCRequest(::grpc::ClientContext* context, const ::imcPersonne::imcPersonneRequest& request, ::imcPersonne::imcResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_IMCRequest_, context, request, response);
}

void imcService::Stub::experimental_async::IMCRequest(::grpc::ClientContext* context, const ::imcPersonne::imcPersonneRequest* request, ::imcPersonne::imcResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_IMCRequest_, context, request, response, std::move(f));
}

void imcService::Stub::experimental_async::IMCRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::imcPersonne::imcResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_IMCRequest_, context, request, response, std::move(f));
}

void imcService::Stub::experimental_async::IMCRequest(::grpc::ClientContext* context, const ::imcPersonne::imcPersonneRequest* request, ::imcPersonne::imcResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_IMCRequest_, context, request, response, reactor);
}

void imcService::Stub::experimental_async::IMCRequest(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::imcPersonne::imcResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_IMCRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::imcPersonne::imcResponse>* imcService::Stub::AsyncIMCRequestRaw(::grpc::ClientContext* context, const ::imcPersonne::imcPersonneRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::imcPersonne::imcResponse>::Create(channel_.get(), cq, rpcmethod_IMCRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::imcPersonne::imcResponse>* imcService::Stub::PrepareAsyncIMCRequestRaw(::grpc::ClientContext* context, const ::imcPersonne::imcPersonneRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::imcPersonne::imcResponse>::Create(channel_.get(), cq, rpcmethod_IMCRequest_, context, request, false);
}

imcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      imcService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< imcService::Service, ::imcPersonne::imcPersonneRequest, ::imcPersonne::imcResponse>(
          [](imcService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::imcPersonne::imcPersonneRequest* req,
             ::imcPersonne::imcResponse* resp) {
               return service->IMCRequest(ctx, req, resp);
             }, this)));
}

imcService::Service::~Service() {
}

::grpc::Status imcService::Service::IMCRequest(::grpc::ServerContext* context, const ::imcPersonne::imcPersonneRequest* request, ::imcPersonne::imcResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace imcPersonne

