// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto
#ifndef GRPC_test_2eproto__INCLUDED
#define GRPC_test_2eproto__INCLUDED

#include "test.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace testHelloWorld {

class TestHelloWorldService final {
 public:
  static constexpr char const* service_full_name() {
    return "testHelloWorld.TestHelloWorldService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::testHelloWorld::HelloResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::testHelloWorld::HelloResponse>> AsynctestHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::testHelloWorld::HelloResponse>>(AsynctestHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::testHelloWorld::HelloResponse>> PrepareAsynctestHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::testHelloWorld::HelloResponse>>(PrepareAsynctestHelloWorldRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void testHelloWorld(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::testHelloWorld::HelloResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void testHelloWorld(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::testHelloWorld::HelloResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void testHelloWorld(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::testHelloWorld::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::testHelloWorld::HelloResponse>* AsynctestHelloWorldRaw(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::testHelloWorld::HelloResponse>* PrepareAsynctestHelloWorldRaw(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::testHelloWorld::HelloResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::testHelloWorld::HelloResponse>> AsynctestHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::testHelloWorld::HelloResponse>>(AsynctestHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::testHelloWorld::HelloResponse>> PrepareAsynctestHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::testHelloWorld::HelloResponse>>(PrepareAsynctestHelloWorldRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response, std::function<void(::grpc::Status)>) override;
      void testHelloWorld(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::testHelloWorld::HelloResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void testHelloWorld(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void testHelloWorld(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::testHelloWorld::HelloResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void testHelloWorld(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::testHelloWorld::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::testHelloWorld::HelloResponse>* AsynctestHelloWorldRaw(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::testHelloWorld::HelloResponse>* PrepareAsynctestHelloWorldRaw(::grpc::ClientContext* context, const ::testHelloWorld::HelloWorld& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_testHelloWorld_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status testHelloWorld(::grpc::ServerContext* context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_testHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_testHelloWorld() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_testHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status testHelloWorld(::grpc::ServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequesttestHelloWorld(::grpc::ServerContext* context, ::testHelloWorld::HelloWorld* request, ::grpc::ServerAsyncResponseWriter< ::testHelloWorld::HelloResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_testHelloWorld<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_testHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_testHelloWorld() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::testHelloWorld::HelloWorld, ::testHelloWorld::HelloResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::testHelloWorld::HelloWorld* request, ::testHelloWorld::HelloResponse* response) { return this->testHelloWorld(context, request, response); }));}
    void SetMessageAllocatorFor_testHelloWorld(
        ::grpc::experimental::MessageAllocator< ::testHelloWorld::HelloWorld, ::testHelloWorld::HelloResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::testHelloWorld::HelloWorld, ::testHelloWorld::HelloResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_testHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status testHelloWorld(::grpc::ServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* testHelloWorld(
      ::grpc::CallbackServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* testHelloWorld(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_testHelloWorld<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_testHelloWorld<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_testHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_testHelloWorld() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_testHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status testHelloWorld(::grpc::ServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_testHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_testHelloWorld() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_testHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status testHelloWorld(::grpc::ServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequesttestHelloWorld(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_testHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_testHelloWorld() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->testHelloWorld(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_testHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status testHelloWorld(::grpc::ServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* testHelloWorld(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* testHelloWorld(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_testHelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_testHelloWorld() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::testHelloWorld::HelloWorld, ::testHelloWorld::HelloResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::testHelloWorld::HelloWorld, ::testHelloWorld::HelloResponse>* streamer) {
                       return this->StreamedtestHelloWorld(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_testHelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status testHelloWorld(::grpc::ServerContext* /*context*/, const ::testHelloWorld::HelloWorld* /*request*/, ::testHelloWorld::HelloResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedtestHelloWorld(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::testHelloWorld::HelloWorld,::testHelloWorld::HelloResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_testHelloWorld<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_testHelloWorld<Service > StreamedService;
};

}  // namespace testHelloWorld


#endif  // GRPC_test_2eproto__INCLUDED
